#!/usr/bin/env bash
set -Eeuo pipefail

# =============================================================================
# GENERATED BUILD ARTIFACT — DO NOT EDIT THIS FILE.
# =============================================================================
#
# Canonical source:
#   https://github.com/thewoolleyman/1password-env-wrapper
#
# Cross-platform (Linux + macOS). The bytes of this file are identical
# whether it was rendered on Linux or macOS for the same inputs; the
# wrapper dispatches on `uname` at runtime to pick the right
# credential-retrieval path.
#
# This file was rendered by create-1password-env-wrapper.sh from the
# wrapper template that lives in that repository. It is NOT
# hand-maintained. Any edit you make here will be SILENTLY REVERTED
# the next time an operator runs the installer (which renders this
# file fresh and overwrites whatever was at this path).
#
# DO NOT edit this file directly under any circumstances — not for
# emergencies, not for one-off debugging, not for "I will copy it
# back into the repo afterwards." If you find a bug or want an
# improvement:
#
#   1. Open the repository above.
#   2. Edit the wrapper template inside create-1password-env-wrapper.sh
#      (or the appropriate spec section in SPECIFICATION.md).
#   3. Open a Pull Request.
#   4. Once merged, rerun the installer on each host to regenerate
#      this file. (`sudo -E ./create-1password-env-wrapper.sh` on
#      Linux; `./create-1password-env-wrapper.sh` without sudo on
#      macOS.)
#
# To regenerate locally with the same inputs you used last time, run
# the installer again from the repository root. The rendering is
# deterministic given the same inputs.
# =============================================================================

# IDENTIFIER is baked in as documentation / for the encrypted-state
# fallback (consumers grep this readonly out of the installed file).
# It is intentionally not referenced inside the wrapper itself.
# shellcheck disable=SC2034
readonly IDENTIFIER='resume'
readonly DEFAULT_SHELL='/bin/bash'
readonly ONEPASSWORD_ENVIRONMENT_ID='fj6btfanxkhmqdrvrtjp2tj5qm'
readonly INSTALLED_WRAPPER='/usr/local/bin/with-resume-env.sh'

# Linux-only constants (referenced only inside the Linux runtime branch).
readonly LINUX_SYSTEMD_CRED_NAME='1password-env-wrapper-resume'
readonly LINUX_SYSTEMD_CRED_PATH='/etc/credstore.encrypted/1password-env-wrapper-resume'

# macOS-only constants (referenced only inside the Darwin runtime branch).
readonly MACOS_KEYCHAIN_SERVICE='resume'
readonly MACOS_KEYCHAIN_TOKEN_ACCOUNT='OP_SERVICE_ACCOUNT_TOKEN'

PROG="$(basename -- "$0")"
err()  { printf '%s: %s\n' "$PROG" "$*" >&2; }
die()  { err "$@"; exit 1; }

# Drop -- separator if present.
if [ "$#" -gt 0 ] && [ "$1" = "--" ]; then
    shift
fi

case "$(uname -s)" in
    Linux)
        # ---------------------------------------------------------------
        # Linux runtime path: 3-stage WRAPPER_STAGE re-exec model.
        # Stage 0: sudo -n self-escalate to root.
        # Stage 1: systemd-creds decrypt the token, setpriv drop back to
        #          the invoker (per SUDO_UID/SUDO_GID/SUDO_USER), re-exec
        #          stage 2 with the token in env.
        # Stage 2: op run --environment, with OP_SERVICE_ACCOUNT_TOKEN
        #          stripped from the final child env.
        # ---------------------------------------------------------------
        case "${WRAPPER_STAGE:-0}" in
            0)
                # Stage 0 — escalate. Always re-exec the *installed* wrapper
                # (not $0, which may be the gitignored rendered build artifact
                # at the repo root) so the sudoers rule only ever needs to
                # whitelist one path.
                # -e (existence) rather than -x (executable): the operator's
                # bash may have started before installer step 10 added them
                # to the IDENTIFIER group, so a 0750 root:<IDENTIFIER> file
                # can fail [ -x ] for them even though sudo (which evaluates
                # /etc/group fresh) will let them escalate to root, where
                # execution is unconstrained by the group bit.
                if [ ! -e "$INSTALLED_WRAPPER" ]; then
                    die "installed wrapper not found at $INSTALLED_WRAPPER (run create-1password-env-wrapper.sh first)"
                fi
                if [ "$(id -u)" -eq 0 ]; then
                    # Already root; jump straight to stage 1 without sudo.
                    # No `--` after the assignment: uutils `env` (and POSIX
                    # `env`) reject a GNU-style `--` separator following
                    # NAME=value operands; the assignment list already ends at
                    # the first non-assignment word.
                    exec env WRAPPER_STAGE=1 "$INSTALLED_WRAPPER" "$@"
                fi
                if ! sudo_path="$(command -v sudo)"; then
                    die "sudo not found on PATH; required to escalate for credential decryption"
                fi
                exec "$sudo_path" -n WRAPPER_STAGE=1 -- "$INSTALLED_WRAPPER" "$@"
                ;;
            1)
                # Stage 1 — running as root. Decrypt the credential into memory,
                # then drop privileges back to the *invoker* (the user who ran
                # sudo to get here, identified by SUDO_UID / SUDO_GID / SUDO_USER
                # which sudo always sets on the elevated process), and re-exec
                # the wrapper as stage 2. We drop to the invoker — not to a
                # separate IDENTIFIER user — so files created or touched by the
                # child command end up owned by whoever invoked the wrapper.
                # See SPECIFICATION.md § Architecture Principles #5.
                [ "$(id -u)" -eq 0 ] || die "stage 1 expected uid 0 (got $(id -u))"
                [ -n "${SUDO_UID:-}" ] \
                    || die "stage 1 expected SUDO_UID in env (sudo did not set it; was the wrapper invoked directly as root without sudo?)"
                [ -n "${SUDO_GID:-}" ] \
                    || die "stage 1 expected SUDO_GID in env"
                [ -n "${SUDO_USER:-}" ] \
                    || die "stage 1 expected SUDO_USER in env"
                invoker_home="$(getent passwd "$SUDO_UID" | cut -d: -f6)"
                [ -n "$invoker_home" ] \
                    || die "could not resolve home directory for SUDO_UID=$SUDO_UID via getent"
                [ -r "$LINUX_SYSTEMD_CRED_PATH" ] \
                    || die "encrypted credential missing or unreadable: $LINUX_SYSTEMD_CRED_PATH"
                if ! token="$(systemd-creds decrypt --name="$LINUX_SYSTEMD_CRED_NAME" "$LINUX_SYSTEMD_CRED_PATH" - 2>/dev/null)"; then
                    die "systemd-creds decrypt failed for $LINUX_SYSTEMD_CRED_PATH"
                fi
                [ -n "$token" ] || die "decrypted credential is empty"

                # OPENV_PRESERVE_VARS (default unset/empty) — generic,
                # caller-controlled allowlist of env var NAMES whose current
                # values are carried THROUGH the `env -i` scrub into the final
                # command. This is the generic mechanism for forwarding a
                # named secret/setting; the wrapper hard-codes no specific name.
                # Names are read from the runtime env, comma-separated;
                # whitespace is trimmed and empty entries are skipped.
                preserve=()
                if [ -n "${OPENV_PRESERVE_VARS:-}" ]; then
                    IFS=',' read -r -a _openv_names <<< "$OPENV_PRESERVE_VARS"
                    for _openv_n in "${_openv_names[@]}"; do
                        # Trim leading/trailing whitespace.
                        _openv_n="${_openv_n#"${_openv_n%%[![:space:]]*}"}"
                        _openv_n="${_openv_n%"${_openv_n##*[![:space:]]}"}"
                        [ -n "$_openv_n" ] || continue
                        preserve+=( "$_openv_n=$(printenv "$_openv_n" 2>/dev/null || true)" )
                    done
                fi

                if [ "${OPENV_KEEP_PRIVILEGES:-0}" = "1" ]; then
                    # OPENV_KEEP_PRIVILEGES=1 — explicit, default-off opt-OUT of
                    # the drop-to-invoker principle (SPECIFICATION.md
                    # § Architecture Principles #5). The command runs at the
                    # wrapper's current uid (root, when reached via sudo) so
                    # admin tooling can reach root-only resources. No setpriv.
                    # No `--` after the env assignments: uutils/POSIX `env`
                    # reject a GNU-style `--` following NAME=value operands.
                    #
                    # HOME must be the CURRENT uid's home, NOT the invoker's:
                    # the child stays root here, and `op run` refuses to use a
                    # config dir under a HOME owned by a different uid ("we
                    # can't safely access \"$HOME/.config/op\" because it's not
                    # owned by the current user"). Resolve the current uid's
                    # home via getent, falling back to /root.
                    keep_home="$(getent passwd "$(id -u)" | cut -d: -f6)"
                    [ -n "$keep_home" ] || keep_home="/root"
                    exec env -i \
                        HOME="$keep_home" \
                        PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
                        OP_SERVICE_ACCOUNT_TOKEN="$token" \
                        WRAPPER_STAGE=2 \
                        "${preserve[@]}" \
                        "$INSTALLED_WRAPPER" "$@"
                else
                    # Default: drop privileges back to the *invoker* via setpriv.
                    # `env` has no trailing `--` (uutils/POSIX reject it after
                    # assignments); setpriv keeps ITS OWN `--` before the command.
                    exec env -i \
                        HOME="$invoker_home" \
                        PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
                        OP_SERVICE_ACCOUNT_TOKEN="$token" \
                        WRAPPER_STAGE=2 \
                        "${preserve[@]}" \
                        setpriv --reuid="$SUDO_UID" --regid="$SUDO_GID" --init-groups -- \
                        "$INSTALLED_WRAPPER" "$@"
                fi
                ;;
            2)
                # Stage 2 — running as the invoker with token in env.
                # Inject variables from the 1Password Environment (NOT from
                # any vault). The wrapper SHALL NOT call op item list,
                # op item get, op read, or any other vault-touching op
                # subcommand — only op run --environment.
                [ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] || die "stage 2 requires OP_SERVICE_ACCOUNT_TOKEN in env"
                unset OP_CONNECT_HOST OP_CONNECT_TOKEN
                # OP_CACHE=false (original hardening default, kept). op's cache
                # does NOT cover `op run --environment` resolution — verified by
                # measuring the service-account rate-limit counter across repeated
                # identical resolutions: consumption is identical with caching on
                # or off. So caching is NOT a rate-limit mitigation here; the real
                # levers are call-volume reduction and the account tier. (The
                # op-exit-9 clause below makes a rate-limit failure legible.)
                export OP_CACHE=false

                if [ "$#" -eq 0 ]; then
                    set -- "$DEFAULT_SHELL" -i
                fi

                # Strip the service-account token AND the internal
                # WRAPPER_STAGE sentinel from the final child env. Unsetting
                # WRAPPER_STAGE lets one wrapper invoke another without the
                # inner wrapper inheriting a stale stage and skipping its own
                # stages. No `env … --`: uutils/POSIX reject the GNU `--`
                # after -u options (op's own `--` before `env` is kept).
                # Do NOT exec op here: observe op's exit status so a 1Password
                # rate-limit failure is legible. op exits 9 when it cannot resolve
                # the Environment because the service-account quota is exhausted
                # (the message is "...rate limit exceeded"). On every other outcome
                # op's exit code is propagated unchanged (the child's own code when
                # it ran). We never capture op/child output — it can carry secrets
                # under --no-masking — so we branch on the exit code alone.
                rc=0
                op run --no-masking --environment "$ONEPASSWORD_ENVIRONMENT_ID" -- \
                    env -u OP_SERVICE_ACCOUNT_TOKEN -u WRAPPER_STAGE "$@" || rc=$?
                if [ "$rc" -eq 9 ]; then
                    err "op run exited 9 — most likely the 1Password service-account rate limit. The account-wide DAILY quota is SHARED across every tenant on this 1Password account and resets on a ~24h window; per-token HOURLY limits reset ~59m. A short retry will NOT clear it — stop and wait, or cut op-run frequency. See https://www.1password.dev/service-accounts/rate-limits/"
                fi
                exit "$rc"
                ;;
            *)
                die "unexpected WRAPPER_STAGE: ${WRAPPER_STAGE}"
                ;;
        esac
        ;;
    Darwin)
        # ---------------------------------------------------------------
        # macOS runtime path: single stage, no privilege escalation.
        # The user's login session is the security boundary; the token
        # sits in the per-user login Keychain, so only that session can
        # read it. Read it, hand it to op run, exec the child.
        # ---------------------------------------------------------------
        if ! token="$(security find-generic-password \
                -s "$MACOS_KEYCHAIN_SERVICE" \
                -a "$MACOS_KEYCHAIN_TOKEN_ACCOUNT" \
                -w 2>/dev/null)"; then
            die "OP_SERVICE_ACCOUNT_TOKEN not found in macOS Keychain (service: $MACOS_KEYCHAIN_SERVICE, account: $MACOS_KEYCHAIN_TOKEN_ACCOUNT). Run create-1password-env-wrapper.sh to seed it."
        fi
        [ -n "$token" ] || die "macOS Keychain entry is empty (service: $MACOS_KEYCHAIN_SERVICE)"
        unset OP_CONNECT_HOST OP_CONNECT_TOKEN
        # OP_CACHE=false (parity with Linux): op does not cache
        # `op run --environment` resolution, so caching is no rate-limit
        # mitigation; the original hardening default is kept.
        export OP_CACHE=false

        if [ "$#" -eq 0 ]; then
            set -- "$DEFAULT_SHELL" -i
        fi

        # Strip the service-account token AND the internal WRAPPER_STAGE
        # sentinel from the final child env, so a nested wrapper invocation
        # does not inherit a stale stage. No `env … --`: uutils/POSIX reject
        # the GNU `--` after assignments/-u options (op's own `--` is kept).
        # Do NOT exec op here (see the Linux Stage-2 note): observe op's exit
        # code so a 1Password rate-limit (op exit 9) is legible, while still
        # propagating the code unchanged. No output is captured (may hold secrets).
        rc=0
        env OP_SERVICE_ACCOUNT_TOKEN="$token" \
            op run --no-masking --environment "$ONEPASSWORD_ENVIRONMENT_ID" -- \
            env -u OP_SERVICE_ACCOUNT_TOKEN -u WRAPPER_STAGE "$@" || rc=$?
        if [ "$rc" -eq 9 ]; then
            err "op run exited 9 — most likely the 1Password service-account rate limit. The account-wide DAILY quota is SHARED across every tenant on this 1Password account and resets on a ~24h window; per-token HOURLY limits reset ~59m. A short retry will NOT clear it — stop and wait. See https://www.1password.dev/service-accounts/rate-limits/"
        fi
        exit "$rc"
        ;;
    *)
        die "unsupported platform: $(uname -s) (only Linux and Darwin are supported)"
        ;;
esac
