#!/usr/bin/env bash
set -Eeuo pipefail

# =============================================================================
# GENERATED BUILD ARTIFACT — DO NOT EDIT THIS FILE.
# =============================================================================
#
# Canonical source:
#   https://github.com/thewoolleyman/1password-env-wrapper
#
# Cross-platform (Linux + macOS). The bytes of this file are identical
# whether it was rendered on Linux or macOS for the same inputs; the
# wrapper dispatches on `uname` at runtime to pick the right
# credential-retrieval path.
#
# This file was rendered by create-1password-env-wrapper.sh from the
# wrapper template that lives in that repository. It is NOT
# hand-maintained. Any edit you make here will be SILENTLY REVERTED
# the next time an operator runs the installer (which renders this
# file fresh and overwrites whatever was at this path).
#
# DO NOT edit this file directly under any circumstances — not for
# emergencies, not for one-off debugging, not for "I will copy it
# back into the repo afterwards." If you find a bug or want an
# improvement:
#
#   1. Open the repository above.
#   2. Edit the wrapper template inside create-1password-env-wrapper.sh
#      (or the appropriate spec section in SPECIFICATION.md).
#   3. Open a Pull Request.
#   4. Once merged, rerun the installer on each host to regenerate
#      this file. (`sudo -E ./create-1password-env-wrapper.sh` on
#      Linux; `./create-1password-env-wrapper.sh` without sudo on
#      macOS.)
#
# To regenerate locally with the same inputs you used last time, run
# the installer again from the repository root. The rendering is
# deterministic given the same inputs.
# =============================================================================

# IDENTIFIER is baked in as documentation / for the encrypted-state
# fallback (consumers grep this readonly out of the installed file).
# It is intentionally not referenced inside the wrapper itself.
# shellcheck disable=SC2034
readonly IDENTIFIER='resume'
readonly DEFAULT_SHELL='/bin/bash'
readonly ONEPASSWORD_ENVIRONMENT_ID='fj6btfanxkhmqdrvrtjp2tj5qm'
readonly INSTALLED_WRAPPER='/usr/local/bin/with-resume-env.sh'

# Linux-only constants (referenced only inside the Linux runtime branch).
readonly LINUX_SYSTEMD_CRED_NAME='1password-env-wrapper-resume'
readonly LINUX_SYSTEMD_CRED_PATH='/etc/credstore.encrypted/1password-env-wrapper-resume'

# macOS-only constants (referenced only inside the Darwin runtime branch).
readonly MACOS_KEYCHAIN_SERVICE='resume'
readonly MACOS_KEYCHAIN_TOKEN_ACCOUNT='OP_SERVICE_ACCOUNT_TOKEN'

PROG="$(basename -- "$0")"
err()  { printf '%s: %s\n' "$PROG" "$*" >&2; }
die()  { err "$@"; exit 1; }
# Shared diagnostic for op's exit code 9 (failed Environment resolution,
# most commonly an exhausted service-account rate limit). Reused by every
# op-run call site below (Linux stage 2's cache-populate resolve and its
# uncached fallback, and the macOS single-stage path) so the wording lives
# in exactly one place.
op_rate_limit_hint() { err "op run exited 9 — most likely the 1Password service-account rate limit. The account-wide DAILY quota is SHARED across every tenant on this 1Password account and resets on a ~24h window; per-token HOURLY limits reset ~59m. A short retry will NOT clear it — stop and wait, or cut op-run frequency. See https://www.1password.dev/service-accounts/rate-limits/"; }

# Drop -- separator if present.
if [ "$#" -gt 0 ] && [ "$1" = "--" ]; then
    shift
fi

case "$(uname -s)" in
    Linux)
        # ---------------------------------------------------------------
        # Linux runtime path: 3-stage WRAPPER_STAGE re-exec model.
        # Stage 0: sudo -n self-escalate to root.
        # Stage 1: systemd-creds decrypt the token, setpriv drop back to
        #          the invoker (per SUDO_UID/SUDO_GID/SUDO_USER), re-exec
        #          stage 2 with the token in env.
        # Stage 2: op run --environment, with OP_SERVICE_ACCOUNT_TOKEN
        #          stripped from the final child env.
        # ---------------------------------------------------------------
        case "${WRAPPER_STAGE:-0}" in
            0)
                # Stage 0 — escalate. Always re-exec the *installed* wrapper
                # (not $0, which may be the gitignored rendered build artifact
                # at the repo root) so the sudoers rule only ever needs to
                # whitelist one path.
                # -e (existence) rather than -x (executable): the operator's
                # bash may have started before installer step 10 added them
                # to the IDENTIFIER group, so a 0750 root:<IDENTIFIER> file
                # can fail [ -x ] for them even though sudo (which evaluates
                # /etc/group fresh) will let them escalate to root, where
                # execution is unconstrained by the group bit.
                if [ ! -e "$INSTALLED_WRAPPER" ]; then
                    die "installed wrapper not found at $INSTALLED_WRAPPER (run create-1password-env-wrapper.sh first)"
                fi
                if [ "$(id -u)" -eq 0 ]; then
                    # Already root; jump straight to stage 1 without sudo.
                    # No `--` after the assignment: uutils `env` (and POSIX
                    # `env`) reject a GNU-style `--` separator following
                    # NAME=value operands; the assignment list already ends at
                    # the first non-assignment word.
                    exec env WRAPPER_STAGE=1 "$INSTALLED_WRAPPER" "$@"
                fi
                if ! sudo_path="$(command -v sudo)"; then
                    die "sudo not found on PATH; required to escalate for credential decryption"
                fi
                # Thread OP_ENV_WRAPPER_CACHE_TTL through explicitly: sudo's
                # default env_reset strips the caller's ambient environment
                # here (the sudoers SETENV tag permits an override, it does
                # not imply preservation), so without this, a caller's
                # OP_ENV_WRAPPER_CACHE_TTL — including =0 to disable caching
                # — would silently fall back to the built-in default on every
                # invocation that reaches here (the common, non-root path).
                # ${VAR:-} degrades a genuinely-unset caller value to an
                # empty string, which stage 2's ${...:-300} default treats
                # the same as unset.
                exec "$sudo_path" -n WRAPPER_STAGE=1 OP_ENV_WRAPPER_CACHE_TTL="${OP_ENV_WRAPPER_CACHE_TTL:-}" -- "$INSTALLED_WRAPPER" "$@"
                ;;
            1)
                # Stage 1 — running as root. Decrypt the credential into memory,
                # then drop privileges back to the *invoker* (the user who ran
                # sudo to get here, identified by SUDO_UID / SUDO_GID / SUDO_USER
                # which sudo always sets on the elevated process), and re-exec
                # the wrapper as stage 2. We drop to the invoker — not to a
                # separate IDENTIFIER user — so files created or touched by the
                # child command end up owned by whoever invoked the wrapper.
                # See SPECIFICATION.md § Architecture Principles #5.
                [ "$(id -u)" -eq 0 ] || die "stage 1 expected uid 0 (got $(id -u))"
                [ -n "${SUDO_UID:-}" ] \
                    || die "stage 1 expected SUDO_UID in env (sudo did not set it; was the wrapper invoked directly as root without sudo?)"
                [ -n "${SUDO_GID:-}" ] \
                    || die "stage 1 expected SUDO_GID in env"
                [ -n "${SUDO_USER:-}" ] \
                    || die "stage 1 expected SUDO_USER in env"
                invoker_home="$(getent passwd "$SUDO_UID" | cut -d: -f6)"
                [ -n "$invoker_home" ] \
                    || die "could not resolve home directory for SUDO_UID=$SUDO_UID via getent"
                [ -r "$LINUX_SYSTEMD_CRED_PATH" ] \
                    || die "encrypted credential missing or unreadable: $LINUX_SYSTEMD_CRED_PATH"
                if ! token="$(systemd-creds decrypt --name="$LINUX_SYSTEMD_CRED_NAME" "$LINUX_SYSTEMD_CRED_PATH" - 2>/dev/null)"; then
                    die "systemd-creds decrypt failed for $LINUX_SYSTEMD_CRED_PATH"
                fi
                [ -n "$token" ] || die "decrypted credential is empty"

                # OPENV_PRESERVE_VARS (default unset/empty) — generic,
                # caller-controlled allowlist of env var NAMES whose current
                # values are carried THROUGH the `env -i` scrub into the final
                # command. This is the generic mechanism for forwarding a
                # named secret/setting; the wrapper hard-codes no specific name.
                # Names are read from the runtime env, comma-separated;
                # whitespace is trimmed and empty entries are skipped.
                preserve=()
                if [ -n "${OPENV_PRESERVE_VARS:-}" ]; then
                    IFS=',' read -r -a _openv_names <<< "$OPENV_PRESERVE_VARS"
                    for _openv_n in "${_openv_names[@]}"; do
                        # Trim leading/trailing whitespace.
                        _openv_n="${_openv_n#"${_openv_n%%[![:space:]]*}"}"
                        _openv_n="${_openv_n%"${_openv_n##*[![:space:]]}"}"
                        [ -n "$_openv_n" ] || continue
                        preserve+=( "$_openv_n=$(printenv "$_openv_n" 2>/dev/null || true)" )
                    done
                fi

                if [ "${OPENV_KEEP_PRIVILEGES:-0}" = "1" ]; then
                    # OPENV_KEEP_PRIVILEGES=1 — explicit, default-off opt-OUT of
                    # the drop-to-invoker principle (SPECIFICATION.md
                    # § Architecture Principles #5). The command runs at the
                    # wrapper's current uid (root, when reached via sudo) so
                    # admin tooling can reach root-only resources. No setpriv.
                    # No `--` after the env assignments: uutils/POSIX `env`
                    # reject a GNU-style `--` following NAME=value operands.
                    #
                    # HOME must be the CURRENT uid's home, NOT the invoker's:
                    # the child stays root here, and `op run` refuses to use a
                    # config dir under a HOME owned by a different uid ("we
                    # can't safely access \"$HOME/.config/op\" because it's not
                    # owned by the current user"). Resolve the current uid's
                    # home via getent, falling back to /root.
                    keep_home="$(getent passwd "$(id -u)" | cut -d: -f6)"
                    [ -n "$keep_home" ] || keep_home="/root"
                    exec env -i \
                        HOME="$keep_home" \
                        PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
                        OP_SERVICE_ACCOUNT_TOKEN="$token" \
                        WRAPPER_STAGE=2 \
                        OP_ENV_WRAPPER_CACHE_TTL="${OP_ENV_WRAPPER_CACHE_TTL:-}" \
                        "${preserve[@]}" \
                        "$INSTALLED_WRAPPER" "$@"
                else
                    # Default: drop privileges back to the *invoker* via setpriv.
                    # `env` has no trailing `--` (uutils/POSIX reject it after
                    # assignments); setpriv keeps ITS OWN `--` before the command.
                    exec env -i \
                        HOME="$invoker_home" \
                        PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
                        OP_SERVICE_ACCOUNT_TOKEN="$token" \
                        WRAPPER_STAGE=2 \
                        OP_ENV_WRAPPER_CACHE_TTL="${OP_ENV_WRAPPER_CACHE_TTL:-}" \
                        "${preserve[@]}" \
                        setpriv --reuid="$SUDO_UID" --regid="$SUDO_GID" --init-groups -- \
                        "$INSTALLED_WRAPPER" "$@"
                fi
                ;;
            2)
                # Stage 2 — running as the invoker with token in env.
                # Inject variables from the 1Password Environment (NOT from
                # any vault). The wrapper SHALL NOT call op item list,
                # op item get, op read, or any other vault-touching op
                # subcommand — only op run --environment.
                [ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] || die "stage 2 requires OP_SERVICE_ACCOUNT_TOKEN in env"
                unset OP_CONNECT_HOST OP_CONNECT_TOKEN
                # OP_CACHE=false (original hardening default, kept). op's cache
                # does NOT cover `op run --environment` resolution — verified by
                # measuring the service-account rate-limit counter across repeated
                # identical resolutions: consumption is identical with caching on
                # or off. So caching is NOT a rate-limit mitigation here; the real
                # levers are call-volume reduction and the account tier. (The
                # op-exit-9 clause below makes a rate-limit failure legible.)
                export OP_CACHE=false

                if [ "$#" -eq 0 ]; then
                    set -- "$DEFAULT_SHELL" -i
                fi

                # ---------------------------------------------------------------
                # TTL cache of the op-RESOLVED VARIABLES (not op's own cache —
                # see the OP_CACHE note above; this is a wrapper-level cache
                # that lets a repeated invocation skip calling op at all).
                # Opt out per-call with OP_ENV_WRAPPER_CACHE_TTL=0; default TTL
                # is 300s, overridable with the same variable.
                #
                # Storage: the invoking user's kernel PERSISTENT keyring
                # (`keyctl get_persistent`), scoped by real uid — the same
                # uid stage 2 always runs as after the setpriv drop, or
                # root's own uid under OPENV_KEEP_PRIVILEGES=1. This is
                # deliberately NOT the plain `@u` user keyring: `setpriv`
                # changes uid via a raw syscall, with no PAM/login session,
                # so the resulting process never gets kernel "Possessor"
                # status over `@u`'s contents — even the process that just
                # created a key there gets only the restrictive default
                # "same uid, non-possessor" permission class back (view
                # only, no read), so a later, separate invocation (even the
                # very same uid) fails to read it with EPERM. The
                # persistent-keyring facility exists precisely for "a
                # uid-scoped keyring usable across separate process
                # invocations without a login session": `get_persistent`
                # both creates-or-fetches it AND links it into the calling
                # process's session, so every invocation is a genuine
                # possessor of it, and reads work correctly. Also chosen
                # over a systemd-creds file because keyring entries live
                # only in kernel memory (never touch disk), are readable
                # only by that uid's own processes (and root), and
                # `keyctl timeout` on the individual cached key gives the
                # KERNEL an expiry, so an expired entry is simply gone
                # rather than stale data this script has to remember to
                # distrust. (The persistent keyring itself also has its own
                # much longer idle-expiry, kernel-default 3 days, which is
                # irrelevant here since every cached key inside it carries
                # its own shorter TTL.)
                #
                # Only the variables op run actually injects are cached — never
                # the wrapper's whole ambient environment — so a cache hit can
                # never replay a stale snapshot of unrelated caller-set
                # variables into a later invocation; it only re-forces the same
                # 1Password-sourced values a live `op run` would have produced
                # (per the "1Password value wins" override rule below). Any
                # cache miss or cache-path anomaly falls through unchanged to
                # the uncached op-run path.
                #
                # Framing is NUL-delimited (`env -0`; `keyctl padd`/`pipe`
                # fed through a real pipe into `mapfile`, never through a
                # bash variable) rather than newline-delimited: a POSIX
                # environment variable name or value cannot contain a NUL
                # byte, so this framing is unambiguous even when a value
                # itself contains a literal newline (e.g. a multi-line PEM
                # private key) — no line-continuation guessing, no risk of
                # misreading a value's own content as a record boundary.
                # `shopt -s lastpipe` makes the last stage of each pipeline
                # below run in this shell rather than a subshell, so
                # `mapfile` can populate arrays used afterward, while
                # `${PIPESTATUS[0]}` still gives the real exit status of the
                # command that produced the piped data.
                # ---------------------------------------------------------------
                shopt -s lastpipe
                cache_ttl="${OP_ENV_WRAPPER_CACHE_TTL:-300}"
                case "$cache_ttl" in
                    ''|*[!0-9]*) cache_ttl=0 ;;  # malformed -> disabled, fail open
                esac

                keyctl_available=0
                command -v keyctl >/dev/null 2>&1 && keyctl_available=1

                persistent_kr=""
                if [ "$cache_ttl" -gt 0 ] && [ "$keyctl_available" -eq 1 ]; then
                    # `|| persistent_kr=""` matters under `set -e`: this is
                    # a bare assignment statement, not part of an `if`
                    # condition, so an unguarded failing command
                    # substitution here would kill the script immediately
                    # instead of falling through to the recovery below.
                    persistent_kr="$(keyctl get_persistent @s 2>/dev/null)" || persistent_kr=""
                    if [ -z "$persistent_kr" ]; then
                        # @s (the session keyring) is unusable — almost
                        # always because it was REVOKED. SSH's PAM stack
                        # (pam_keyinit.so force revoke) revokes @s at logout
                        # but never refreshes it for a process that outlives
                        # that login (a detached tmux server reparented to
                        # init, a long-lived daemon, sudo — which has no
                        # pam_keyinit of its own and so only ever INHERITS
                        # whatever @s it was handed). @s is still the right
                        # destination (it's what children inherit, unlike @u
                        # which loses "possessor" status across the setpriv
                        # privilege drop above) — it just needs to be fresh.
                        #
                        # `keyctl new_session` performs the same join
                        # operation as `keyctl session -` on THIS
                        # already-running process — no exec, no child, no
                        # re-entry into this script. That makes it strictly
                        # safer AND simpler than a re-exec-based recovery:
                        # if it fails (e.g. a keyring quota exceeded), this
                        # process is completely unaffected and simply falls
                        # through to the uncached path below, exactly like
                        # any other cache-path anomaly — there is no
                        # "committed to something destructive" step to
                        # guard, no probe-then-commit dance, and no
                        # recursion to bound, because nothing ever re-enters
                        # this script.
                        #
                        # MEASURED, not merely reasoned: this is NOT purely
                        # local to this process. A process whose @s was
                        # revoked/absent falls back to a shared per-uid
                        # keyring, and `keyctl new_session` appears to
                        # re-mint THAT shared fallback — a sibling process in
                        # the same state healed the instant this ran, with
                        # no re-exec of its own. Confirmed this does NOT
                        # disturb a process that already has its own
                        # distinct, healthy session keyring (a live @s is
                        # simply not looking at the shared fallback in the
                        # first place). Documented as measured behavior, not
                        # theory, because the exact kernel mechanism wasn't
                        # independently verified beyond this observation.
                        #
                        # `>/dev/null 2>&1` on BOTH streams is load-bearing,
                        # not cosmetic: `keyctl new_session` prints a bare
                        # keyring ID to STDOUT (confirmed; `keyctl session`'s
                        # "Joined session keyring: N" banner, by contrast,
                        # goes to stderr). A real downstream caller merged
                        # stdout+stderr around a wrapped JSON-emitting
                        # command and had that banner corrupt its output —
                        # the stdout case here is the same hazard but worse,
                        # since it would corrupt EVERY caller's payload
                        # channel, not only ones that merge streams.
                        if keyctl new_session >/dev/null 2>&1; then
                            persistent_kr="$(keyctl get_persistent @s 2>/dev/null)" || persistent_kr=""
                            if [ -n "$persistent_kr" ]; then
                                # Quiet by default: on a host where @s is
                                # revoked by construction (see above), this
                                # is the NORMAL path, not an anomaly, and
                                # would otherwise fire on essentially every
                                # invocation, training callers to filter it
                                # out. Only a genuine bypass (below, and the
                                # other two cache-path anomalies) stays loud
                                # unconditionally.
                                if [ "${OP_ENV_WRAPPER_DEBUG:-0}" = 1 ]; then
                                    err "TTL cache: session keyring (@s) was unusable (commonly: revoked by a dead login session) — recovered by joining a fresh one in place"
                                fi
                            else
                                err "TTL cache bypassed: joined a fresh session keyring but still could not obtain the persistent keyring — falling back to the uncached path"
                            fi
                        else
                            err "TTL cache bypassed: session keyring (@s) is unusable and a fresh one could not be created (kernel.keys.maxkeys/maxbytes quota exceeded, or keyctl is non-functional here) — falling back to the uncached path"
                        fi
                    fi
                elif [ "$cache_ttl" -gt 0 ]; then
                    err "TTL cache bypassed: keyctl not found on PATH (install keyutils to enable caching) — falling back to the uncached path"
                fi

                if [ -n "$persistent_kr" ]; then
                    cache_desc="op-env-wrapper-cache:${IDENTIFIER}:${ONEPASSWORD_ENVIRONMENT_ID}"

                    # --- cache hit? ---
                    assign=()
                    if key_id="$(keyctl search "$persistent_kr" user "$cache_desc" 2>/dev/null)"; then
                        keyctl pipe "$key_id" 2>/dev/null | mapfile -d '' -t assign
                        # Sanity-check every replayed entry looks like
                        # NAME=VALUE before trusting it as an `env` operand —
                        # a value missing '=' entirely would otherwise be
                        # interpreted by `env` as the START OF THE COMMAND
                        # rather than an assignment. This guards only against
                        # a corrupted/incompatible cache entry, never against
                        # legitimate multi-line values (NUL framing already
                        # makes those unambiguous).
                        for kv in "${assign[@]}"; do
                            case "$kv" in
                                *=*) ;;
                                *) assign=(); break ;;
                            esac
                        done
                    fi
                    if [ "${#assign[@]}" -gt 0 ]; then
                        exec env -u OP_SERVICE_ACCOUNT_TOKEN -u WRAPPER_STAGE "${assign[@]}" "$@"
                    fi

                    # --- cache miss: resolve via an introspection target
                    # (`env -0`, not the real command) so we learn exactly
                    # which variables op injected, cache that diff, then
                    # launch the real command ourselves. This is the ONLY
                    # `op run` call on a cache miss — the real command never
                    # runs under op.
                    env -u OP_SERVICE_ACCOUNT_TOKEN -u WRAPPER_STAGE -0 | mapfile -d '' -t baseline_arr
                    declare -A base_map=()
                    for kv in "${baseline_arr[@]}"; do
                        base_map["${kv%%=*}"]="${kv#*=}"
                    done

                    op run --no-masking --environment "$ONEPASSWORD_ENVIRONMENT_ID" -- env -u OP_SERVICE_ACCOUNT_TOKEN -u WRAPPER_STAGE -0 | mapfile -d '' -t resolved_arr
                    op_rc="${PIPESTATUS[0]}"
                    if [ "$op_rc" -eq 0 ]; then
                        assign=()
                        injected=()
                        for kv in "${resolved_arr[@]}"; do
                            assign+=("$kv")
                            name="${kv%%=*}"
                            value="${kv#*=}"
                            if [ "${base_map[$name]+set}" != "set" ] || [ "${base_map[$name]}" != "$value" ]; then
                                injected+=("$kv")
                            fi
                        done
                        if [ "${#injected[@]}" -gt 0 ]; then
                            if new_key_id="$(printf '%s\0' "${injected[@]}" | keyctl padd user "$cache_desc" "$persistent_kr" 2>/dev/null)"; then
                                keyctl timeout "$new_key_id" "$cache_ttl" >/dev/null 2>&1 || true
                            else
                                err "TTL cache: failed to store the resolved Environment (commonly: kernel.keys.maxbytes/maxkeys quota exceeded on the persistent keyring) — this invocation still succeeds, but every call will keep resolving via op run (one more draw on the 1Password service account's SHARED DAILY quota) until the keyring quota is freed"
                            fi
                        fi
                        exec env -u OP_SERVICE_ACCOUNT_TOKEN -u WRAPPER_STAGE "${assign[@]}" "$@"
                    fi
                    if [ "$op_rc" -eq 9 ]; then
                        op_rate_limit_hint
                    fi
                    exit "$op_rc"
                fi

                # Uncached path: caching disabled (OP_ENV_WRAPPER_CACHE_TTL=0),
                # keyctl unavailable, or a cache-path anomaly above. Identical
                # to the wrapper's pre-cache behavior.
                # Strip the service-account token AND the internal
                # WRAPPER_STAGE sentinel from the final child env. Unsetting
                # WRAPPER_STAGE lets one wrapper invoke another without the
                # inner wrapper inheriting a stale stage and skipping its own
                # stages. No `env … --`: uutils/POSIX reject the GNU `--`
                # after -u options (op's own `--` before `env` is kept).
                # Do NOT exec op here: observe op's exit status so a 1Password
                # rate-limit failure is legible. op exits 9 when it cannot resolve
                # the Environment because the service-account quota is exhausted
                # (the message is "...rate limit exceeded"). On every other outcome
                # op's exit code is propagated unchanged (the child's own code when
                # it ran). We never capture op/child output — it can carry secrets
                # under --no-masking — so we branch on the exit code alone.
                rc=0
                op run --no-masking --environment "$ONEPASSWORD_ENVIRONMENT_ID" -- \
                    env -u OP_SERVICE_ACCOUNT_TOKEN -u WRAPPER_STAGE "$@" || rc=$?
                if [ "$rc" -eq 9 ]; then
                    op_rate_limit_hint
                fi
                exit "$rc"
                ;;
            *)
                die "unexpected WRAPPER_STAGE: ${WRAPPER_STAGE}"
                ;;
        esac
        ;;
    Darwin)
        # ---------------------------------------------------------------
        # macOS runtime path: single stage, no privilege escalation.
        # The user's login session is the security boundary; the token
        # sits in the per-user login Keychain, so only that session can
        # read it. Read it, hand it to op run, exec the child.
        # ---------------------------------------------------------------
        if ! token="$(security find-generic-password \
                -s "$MACOS_KEYCHAIN_SERVICE" \
                -a "$MACOS_KEYCHAIN_TOKEN_ACCOUNT" \
                -w 2>/dev/null)"; then
            die "OP_SERVICE_ACCOUNT_TOKEN not found in macOS Keychain (service: $MACOS_KEYCHAIN_SERVICE, account: $MACOS_KEYCHAIN_TOKEN_ACCOUNT). Run create-1password-env-wrapper.sh to seed it."
        fi
        [ -n "$token" ] || die "macOS Keychain entry is empty (service: $MACOS_KEYCHAIN_SERVICE)"
        unset OP_CONNECT_HOST OP_CONNECT_TOKEN
        # OP_CACHE=false (parity with Linux): op does not cache
        # `op run --environment` resolution, so caching is no rate-limit
        # mitigation; the original hardening default is kept.
        export OP_CACHE=false

        if [ "$#" -eq 0 ]; then
            set -- "$DEFAULT_SHELL" -i
        fi

        # Strip the service-account token AND the internal WRAPPER_STAGE
        # sentinel from the final child env, so a nested wrapper invocation
        # does not inherit a stale stage. No `env … --`: uutils/POSIX reject
        # the GNU `--` after assignments/-u options (op's own `--` is kept).
        # Do NOT exec op here (see the Linux Stage-2 note): observe op's exit
        # code so a 1Password rate-limit (op exit 9) is legible, while still
        # propagating the code unchanged. No output is captured (may hold secrets).
        rc=0
        env OP_SERVICE_ACCOUNT_TOKEN="$token" \
            op run --no-masking --environment "$ONEPASSWORD_ENVIRONMENT_ID" -- \
            env -u OP_SERVICE_ACCOUNT_TOKEN -u WRAPPER_STAGE "$@" || rc=$?
        if [ "$rc" -eq 9 ]; then
            op_rate_limit_hint
        fi
        exit "$rc"
        ;;
    *)
        die "unsupported platform: $(uname -s) (only Linux and Darwin are supported)"
        ;;
esac
