// Harness test for GitHub CI and pull-request automation.
//
// Pins SPECIFICATION/non-functional-requirements.md §"GitHub CI and pull
// request discipline" and §"Pull request landing automation":
// .github/workflows/check.yml runs `bun run check` on pull requests
// targeting master and pushes to master with the pinned Bun toolchain, a
// lockfile install, and a full-history checkout (the TDD range validator
// must not see a shallow base); CI delegates to named Bun scripts only;
// .github/workflows/auto-enable-merge.yml enables rebase auto-merge for
// eligible owner PRs via a short-lived GitHub App token (APP_ID /
// APP_PRIVATE_KEY), skipping drafts and do-not-merge labels; no
// auto-update-branches mechanism exists; and the required status-check
// name, merge-method, and branch-protection settings are documented and
// locally verified by scripts/check-ci.ts inside `bun run check`.

import { afterAll, describe, expect, setDefaultTimeout, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// The CI-verification checks spawn subprocesses; raise the per-test budget
// above Bun's 5s default so they do not flake under concurrent load.
setDefaultTimeout(60_000);

const repoRoot = join(import.meta.dir, "..");
const ciScript = join(repoRoot, "scripts", "check-ci.ts");

const fixtures: string[] = [];
afterAll(() => {
  for (const dir of fixtures) {
    rmSync(dir, { recursive: true, force: true });
  }
});

const VALID_CHECK_YML = `name: check
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - run: bun install --frozen-lockfile
      - run: bun run check
`;

const VALID_AUTO_MERGE_YML = `name: auto-enable-merge
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize, unlabeled]
jobs:
  enable-auto-merge:
    if: >-
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'do-not-merge') &&
      github.event.pull_request.user.login == github.repository_owner
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: \${{ secrets.APP_ID }}
          private-key: \${{ secrets.APP_PRIVATE_KEY }}
      - env:
          GH_TOKEN: \${{ steps.app-token.outputs.token }}
          PR: \${{ github.event.pull_request.number }}
          REPO: \${{ github.repository }}
        run: gh pr merge "$PR" --repo "$REPO" --auto --rebase
`;

const VALID_GITHUB_README = `# GitHub automation

Required status check: \`check\` (the check.yml job name); branch
protection must require it before auto-merge, with strict mode NOT
enabled. Merge methods: rebase only — squash and merge commits are
disabled; master requires linear history (applies to administrators via
a ruleset) while direct owner pushes stay permitted. Auto-merge needs
the APP_ID and APP_PRIVATE_KEY GitHub App secrets; PRs labeled
do-not-merge are skipped. Local secret-needing commands inject their
secrets through the with-resume-env.sh wrapper — render pending
maintainer 1Password bootstrap.
`;

// Once the wrapper is committed, the docs must stop calling it pending.
const VALID_GITHUB_README_WRAPPER_LANDED = VALID_GITHUB_README.replace(
  " — render pending\nmaintainer 1Password bootstrap",
  "",
);

const VALID_SCRIPTS_README = `# scripts

Live GitHub verification runs with CHECK_LIVE_GITHUB=1; secret-needing
commands run through the committed with-resume-env.sh wrapper.
`;

// A shape-valid rendered wrapper: generated-artifact header, the resume
// identifier, environment injection via op run, and no secret values.
const VALID_WRAPPER = `#!/usr/bin/env bash
# GENERATED BUILD ARTIFACT — DO NOT EDIT THIS FILE.
# Rendered by create-1password-env-wrapper.sh; see
# https://github.com/thewoolleyman/1password-env-wrapper
readonly IDENTIFIER='resume'
readonly ONEPASSWORD_ENVIRONMENT_ID='exampleenvironmentid00000'
exec op run --no-masking --environment "$ONEPASSWORD_ENVIRONMENT_ID" -- "$@"
`;

// A pinned-consumer bump lane that CAN run unattended: a daily schedule, a
// pull resolve of the source repository's latest release, and a pull request
// opened for an identity auto-enable-merge allowlists.
const VALID_BUMP_PIN_YML = `name: bump-plugin-pin
on:
  repository_dispatch:
    types: [sibling-released]
  schedule:
    - cron: "37 6 * * *"
  workflow_dispatch:
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - run: gh api "repos/$OWNER/$SOURCE_REPO/releases/latest" --jq '.tag_name'
      - run: gh pr create --base master --head "$branch" --title bump
`;

// auto-enable-merge that allowlists an automation identity beside the owner.
const AUTO_MERGE_YML_WITH_BOT = VALID_AUTO_MERGE_YML.replace(
  "      github.event.pull_request.user.login == github.repository_owner",
  `      (
        github.event.pull_request.user.login == github.repository_owner ||
        github.event.pull_request.user.login == 'resume-pr-bot[bot]'
      )`,
);

// A direct-push lane whose HEADER COMMENT happens to contain "gh pr create"
// — openbrain's real shape: its comment describes a past run that failed at
// that step, while the lane itself pushes. A raw-text scan demands an
// auto-merge allowlist from it; a parsed scan correctly does not.
const BUMP_PIN_YML_PUSHES_BUT_COMMENT_MENTIONS_PR = `# This lane lands by direct
# push. An earlier revision opened a pull request and failed at \`gh pr create\`,
# which is why it does not any more.
name: bump-plugin-pin
on:
  schedule:
    - cron: "37 6 * * *"
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - run: gh api "repos/$OWNER/$SOURCE_REPO/releases/latest" --jq '.tag_name'
      - run: git push origin HEAD:master
`;

// The pull resolve named only in a comment: the lane cannot actually resolve a
// tag, so a scheduled run — which carries no payload and no input — dies.
const BUMP_PIN_YML_RESOLVE_ONLY_IN_A_COMMENT = `name: bump-plugin-pin
on:
  schedule:
    - cron: "37 6 * * *"
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      # Resolves the newest tag via repos/OWNER/REPO/releases/latest.
      - run: echo "$TAG_FROM_PAYLOAD"
      - run: git push origin HEAD:master
`;

// The trap this suite exists to keep shut: the bot named ONLY in a comment.
// A raw-text scan for "[bot]" accepts this file; the eligibility expression
// still allowlists nobody, so the bump pull request still waits for a human.
const AUTO_MERGE_YML_BOT_ONLY_IN_A_COMMENT = VALID_AUTO_MERGE_YML.replace(
  "name: auto-enable-merge",
  "# Trusted automation identities such as resume-pr-bot[bot] land here.\nname: auto-enable-merge",
);

interface FixtureOptions {
  readonly checkYml?: string | null;
  readonly autoMergeYml?: string | null;
  readonly bumpPinYml?: string | null;
  readonly readme?: string | null;
  readonly scriptsReadme?: string | null;
  readonly wrapper?: string | null;
  readonly extraWorkflow?: { name: string; content: string };
  readonly withoutWorkflowsDir?: boolean;
}

function makeFixture(options: FixtureOptions = {}): string {
  const dir = mkdtempSync(join(tmpdir(), "resume-ci-fixture-"));
  fixtures.push(dir);
  writeFileSync(
    join(dir, "package.json"),
    JSON.stringify({
      name: "fixture",
      private: true,
      scripts: { check: "true" },
    }),
  );
  if (options.withoutWorkflowsDir) {
    return dir;
  }
  mkdirSync(join(dir, ".github", "workflows"), { recursive: true });
  const checkYml =
    options.checkYml === undefined ? VALID_CHECK_YML : options.checkYml;
  if (checkYml !== null) {
    writeFileSync(join(dir, ".github", "workflows", "check.yml"), checkYml);
  }
  const autoMergeYml =
    options.autoMergeYml === undefined
      ? VALID_AUTO_MERGE_YML
      : options.autoMergeYml;
  if (autoMergeYml !== null) {
    writeFileSync(
      join(dir, ".github", "workflows", "auto-enable-merge.yml"),
      autoMergeYml,
    );
  }
  const readme =
    options.readme === undefined ? VALID_GITHUB_README : options.readme;
  if (readme !== null) {
    writeFileSync(join(dir, ".github", "README.md"), readme);
  }
  const scriptsReadme =
    options.scriptsReadme === undefined
      ? VALID_SCRIPTS_README
      : options.scriptsReadme;
  if (scriptsReadme !== null) {
    mkdirSync(join(dir, "scripts"), { recursive: true });
    writeFileSync(join(dir, "scripts", "README.md"), scriptsReadme);
  }
  if (options.wrapper !== undefined && options.wrapper !== null) {
    writeFileSync(join(dir, "with-resume-env.sh"), options.wrapper);
  }
  // Absent by DEFAULT: a repository without a bump lane is not a pinned
  // consumer and is not in violation, so every pre-existing fixture keeps
  // passing untouched.
  if (options.bumpPinYml !== undefined && options.bumpPinYml !== null) {
    writeFileSync(
      join(dir, ".github", "workflows", "bump-plugin-pin.yml"),
      options.bumpPinYml,
    );
  }
  if (options.extraWorkflow !== undefined) {
    writeFileSync(
      join(dir, ".github", "workflows", options.extraWorkflow.name),
      options.extraWorkflow.content,
    );
  }
  return dir;
}

function runCi(root: string): { exitCode: number | null; output: string } {
  const run = Bun.spawnSync({
    cmd: ["bun", ciScript, "--project-root", root],
    cwd: repoRoot,
  });
  return {
    exitCode: run.exitCode,
    output: run.stdout.toString() + run.stderr.toString(),
  };
}

describe("GitHub CI and pull-request automation gate (li-xjjeqo)", () => {
  test("the repository's committed workflows and docs pass local verification", () => {
    const { exitCode, output } = runCi(repoRoot);
    expect(output).not.toContain("FAIL");
    expect(exitCode).toBe(0);
  });

  test("a shape-valid fixture passes", () => {
    expect(runCi(makeFixture()).exitCode).toBe(0);
  });

  test("a missing workflows directory is a precondition failure (exit 3)", () => {
    expect(runCi(makeFixture({ withoutWorkflowsDir: true })).exitCode).toBe(3);
  });

  test("a missing check.yml fails, naming it", () => {
    const { exitCode, output } = runCi(makeFixture({ checkYml: null }));
    expect(exitCode).toBe(1);
    expect(output).toContain("check.yml");
  });

  test("check.yml without the push-to-master trigger fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        checkYml: VALID_CHECK_YML.replace(
          "  push:\n    branches: [master]\n",
          "",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("push");
  });

  test("check.yml without a full-history checkout fails (shallow TDD range base)", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        checkYml: VALID_CHECK_YML.replace(
          "        with:\n          fetch-depth: 0\n",
          "",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("fetch-depth");
  });

  test("check.yml without a pinned Bun setup fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        checkYml: VALID_CHECK_YML.replace(
          "        with:\n          bun-version-file: package.json\n",
          "",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("setup-bun");
  });

  test("check.yml without the frozen-lockfile install fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        checkYml: VALID_CHECK_YML.replace(
          "      - run: bun install --frozen-lockfile\n",
          "",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("frozen-lockfile");
  });

  test("a run step invoking a script that package.json does not name fails (delegation)", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        checkYml: VALID_CHECK_YML.replace(
          "      - run: bun run check\n",
          "      - run: bun run check\n      - run: bun run mystery-gate\n",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("mystery-gate");
  });

  test("auto-enable-merge.yml missing the unlabeled trigger fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        autoMergeYml: VALID_AUTO_MERGE_YML.replace(
          "types: [opened, reopened, ready_for_review, synchronize, unlabeled]",
          "types: [opened, reopened, ready_for_review, synchronize]",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("unlabeled");
  });

  test("auto-enable-merge.yml without the do-not-merge skip fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        autoMergeYml: VALID_AUTO_MERGE_YML.replace(
          "      !contains(github.event.pull_request.labels.*.name, 'do-not-merge') &&\n",
          "",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("do-not-merge");
  });

  test("auto-enable-merge.yml without the GitHub App token mint fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        autoMergeYml: VALID_AUTO_MERGE_YML.replace(
          "actions/create-github-app-token@v1",
          "nobody/some-other-action@v1",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("create-github-app-token");
  });

  test("auto-enable-merge.yml without rebase auto-merge enablement fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        autoMergeYml: VALID_AUTO_MERGE_YML.replace(
          'run: gh pr merge "$PR" --repo "$REPO" --auto --rebase',
          'run: echo "$PR"',
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("--auto --rebase");
  });

  test("an auto-update-branches mechanism is rejected", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        extraWorkflow: {
          name: "keep-branches-fresh.yml",
          content:
            "name: keep-branches-fresh\non:\n  push:\n    branches: [master]\njobs:\n  update:\n    runs-on: ubuntu-latest\n    steps:\n      - run: gh pr update-branch 1\n",
        },
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("update-branch");
  });

  test("missing settings documentation fails, naming the doc", () => {
    const { exitCode, output } = runCi(makeFixture({ readme: null }));
    expect(exitCode).toBe(1);
    expect(output).toContain(".github/README.md");
  });

  test("documentation missing the App secrets fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        readme: VALID_GITHUB_README.replace("APP_PRIVATE_KEY", "SOMETHING"),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("APP_PRIVATE_KEY");
  });

  test("documentation missing the local secret-injection wrapper fails (NFR §Local secret injection)", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        readme: VALID_GITHUB_README.replace(
          "with-resume-env.sh",
          "some-other-mechanism",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("with-resume-env.sh");
  });

  test("scripts/README.md missing wrapper usage for secret-needing commands fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        scriptsReadme: VALID_SCRIPTS_README.replace(
          "with-resume-env.sh",
          "plain env vars",
        ),
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("scripts/README.md");
  });

  test("a missing scripts/README.md fails, naming it", () => {
    const { exitCode, output } = runCi(makeFixture({ scriptsReadme: null }));
    expect(exitCode).toBe(1);
    expect(output).toContain("scripts/README.md");
  });

  test("a shape-valid committed wrapper passes", () => {
    expect(
      runCi(
        makeFixture({
          wrapper: VALID_WRAPPER,
          readme: VALID_GITHUB_README_WRAPPER_LANDED,
        }),
      ).exitCode,
    ).toBe(0);
  });

  test("an absent wrapper with no documented pending state fails (docs must not claim a committed wrapper)", () => {
    const { exitCode, output } = runCi(
      makeFixture({ readme: VALID_GITHUB_README_WRAPPER_LANDED }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("pending");
    expect(output).toContain("with-resume-env.sh");
  });

  test("a committed wrapper with a stale pending marker fails", () => {
    const { exitCode, output } = runCi(makeFixture({ wrapper: VALID_WRAPPER }));
    expect(exitCode).toBe(1);
    expect(output).toContain("pending");
  });

  test("a committed wrapper carrying a service-account token fails (no secret values)", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        wrapper: VALID_WRAPPER.replace(
          "exec op run",
          'OP_SERVICE_ACCOUNT_TOKEN="ops_notarealtokenbutshapedlikeone1234567890abcdef"\nexec op run',
        ),
        readme: VALID_GITHUB_README_WRAPPER_LANDED,
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("secret");
  });

  test("a committed wrapper without the generated-artifact header fails (hand-edit guard)", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        wrapper: VALID_WRAPPER.replace(
          "# GENERATED BUILD ARTIFACT — DO NOT EDIT THIS FILE.\n",
          "",
        ),
        readme: VALID_GITHUB_README_WRAPPER_LANDED,
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("generated");
  });

  test("a committed wrapper for a different identifier fails", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        wrapper: VALID_WRAPPER.replace(
          "readonly IDENTIFIER='resume'",
          "readonly IDENTIFIER='someoneelse'",
        ),
        readme: VALID_GITHUB_README_WRAPPER_LANDED,
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("resume");
  });

  test("the aggregate check runs the CI verification as an operational gate", () => {
    const run = Bun.spawnSync({
      cmd: [
        "bun",
        join(repoRoot, "scripts", "check.ts"),
        "--project-root",
        repoRoot,
      ],
      cwd: repoRoot,
      env: {
        ...process.env,
        CHECK_SKIP_HARNESS_TESTS: "1",
        CHECK_SKIP_TOOLCHAIN_RUNNERS: "1",
        CHECK_SKIP_BUILD: "1",
        CHECK_SKIP_E2E: "1",
        CHECK_SKIP_COVERAGE: "1",
      },
    });
    const output = run.stdout.toString() + run.stderr.toString();
    const gateLine = output
      .split("\n")
      .find((line) => line.includes("ci delegation and workflow verification"));
    expect(gateLine).toBeDefined();
    expect(gateLine).toContain("[ok]");
    expect(run.exitCode).toBe(0);
  }, 240000);
});

describe("the pinned-consumer bump lane must be able to run unattended", () => {
  test("a repository with no bump lane is not in violation", () => {
    expect(runCi(makeFixture()).exitCode).toBe(0);
  });

  test("a bump lane with a schedule, a pull resolve, and an allowlisted bot passes", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        bumpPinYml: VALID_BUMP_PIN_YML,
        autoMergeYml: AUTO_MERGE_YML_WITH_BOT,
      }),
    );
    expect(output).not.toContain("FAIL");
    expect(exitCode).toBe(0);
  });

  test("a bump lane with no schedule trigger fails — the dispatch hop is unauthorized by design, so nothing else would ever advance the pin", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        bumpPinYml: VALID_BUMP_PIN_YML.replace(
          '  schedule:\n    - cron: "37 6 * * *"\n',
          "",
        ),
        autoMergeYml: AUTO_MERGE_YML_WITH_BOT,
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("`schedule` trigger");
  });

  test("a bump lane that cannot resolve the latest release fails — a scheduled run carries neither a payload nor an input", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        bumpPinYml: VALID_BUMP_PIN_YML.replace(
          "releases/latest",
          "tags/pinned",
        ),
        autoMergeYml: AUTO_MERGE_YML_WITH_BOT,
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("releases/latest");
  });

  test("a bump lane that opens a pull request fails when auto-enable-merge allowlists no automation identity", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        bumpPinYml: VALID_BUMP_PIN_YML,
        autoMergeYml: VALID_AUTO_MERGE_YML,
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("allowlists no automation identity");
  });

  // THE TOOTHLESS-VERIFIER REGRESSION. The first draft of this check scanned
  // the raw auto-enable-merge.yml text for "[bot]" and stayed GREEN under the
  // sabotage above, because the file's own comment block names the bot in
  // prose. Reading the PARSED job `if` is what gives the check teeth; this test
  // fails if anyone reverts it to a text scan.
  test("a bot named only in a COMMENT does not satisfy the allowlist", () => {
    // The trap is only meaningful if the fixture really would satisfy a raw
    // text scan, so assert that about the FIXTURE before asserting the check
    // rejects it anyway. Without this line the test could pass against a
    // fixture that had quietly lost the comment.
    expect(AUTO_MERGE_YML_BOT_ONLY_IN_A_COMMENT).toContain(
      "resume-pr-bot[bot]",
    );
    const { exitCode, output } = runCi(
      makeFixture({
        bumpPinYml: VALID_BUMP_PIN_YML,
        autoMergeYml: AUTO_MERGE_YML_BOT_ONLY_IN_A_COMMENT,
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("allowlists no automation identity");
  });

  // The control for every refusal above: a lane that does NOT open a pull
  // request needs no allowlist at all — openbrain's shape, which pushes
  // directly to its default branch and so never waits on a merge decision.
  // THE MIRROR-IMAGE FALSE POSITIVE. A raw-text scan for "gh pr create" also
  // misfires the other way: openbrain's real lane pushes directly, but its
  // header comment contains that exact string describing a past failure. Under
  // a raw scan that lane is told to add an auto-merge allowlist it does not
  // need — a check that fails correct configurations is as bad as one that
  // passes broken ones.
  test("a direct-push lane is not accused merely because a COMMENT says gh pr create", () => {
    expect(BUMP_PIN_YML_PUSHES_BUT_COMMENT_MENTIONS_PR).toContain(
      "gh pr create",
    );
    const { exitCode, output } = runCi(
      makeFixture({
        bumpPinYml: BUMP_PIN_YML_PUSHES_BUT_COMMENT_MENTIONS_PR,
        autoMergeYml: VALID_AUTO_MERGE_YML,
      }),
    );
    expect(output).not.toContain("allowlists no automation identity");
    expect(exitCode).toBe(0);
  });

  test("a pull resolve named only in a COMMENT does not count as resolving", () => {
    expect(BUMP_PIN_YML_RESOLVE_ONLY_IN_A_COMMENT).toContain("releases/latest");
    const { exitCode, output } = runCi(
      makeFixture({
        bumpPinYml: BUMP_PIN_YML_RESOLVE_ONLY_IN_A_COMMENT,
        autoMergeYml: VALID_AUTO_MERGE_YML,
      }),
    );
    expect(exitCode).toBe(1);
    expect(output).toContain("releases/latest");
  });

  test("a bump lane that pushes directly needs no allowlist", () => {
    const { exitCode, output } = runCi(
      makeFixture({
        bumpPinYml: VALID_BUMP_PIN_YML.replace(
          '      - run: gh pr create --base master --head "$branch" --title bump\n',
          "      - run: git push origin HEAD:master\n",
        ),
        autoMergeYml: VALID_AUTO_MERGE_YML,
      }),
    );
    expect(output).not.toContain("FAIL");
    expect(exitCode).toBe(0);
  });
});
